Integrated Erdstall interface and updated build scripts
BP-NFT-Game/NFT_Game pull request #1
Opened 2021-12-16 11:21 UTC by johannesscha

npm install -d now creates interface bundle file. Interface functions can be globally accessed by erdstallInterface.foo()

2021-12-17 10:21 UTC, DeltaTecs commented on .gitignore
> +package-lock.json
wofür isn das?

2021-12-17 10:25 UTC, DeltaTecs approved these changes
Ich würde noch den auskommentierten code aus erdstallinterface.ts rausnehmen und dafür vllt ein zwei Kommentare über die Funktionen schreiben was die machen (Falls du erdstallinterface.ts modifiziert hast, wenn nicht würd ich es so lassen, ist ja nicht unser job hinter Perun aufzuräumen)

2021-12-17 10:28 UTC, DeltaTecs approved these changes
Ein paar Kommentare und weniger auskommentierter Code (oder beschreib warum er auskommentiert ist und wann man ihn wieder einkommentieren kann) wären nice

2021-12-17 13:48 UTC, DeltaTecs approved these changes

2021-12-17 13:57 UTC, DeltaTecs requested changes
Da die beiden interfaces neu sind und wir häufig mit denen arbeiten werden, würde ich jeder Methode einen Kommentar anfügen was die eigentlich macht

2021-12-17 13:58 UTC, JaSilasJa approved these changes

2021-12-20 17:18 UTC, NiDoJu approved these changes

2021-12-20 23:42 UTC, eap1407 approved these changes

2021-12-21 10:14 UTC, merged