Nft communication
BP-NFT-Game/NFT_Game pull request #27
Opened 2022-01-25 15:13 UTC by DeltaTecs

Bilder werden generiert und vom client abgerfragt. NFT keys in entities übermittelt und NFT sprites gerendert

2022-01-25 19:43 UTC, JaSilasJa commented on client/js/game.js
> +                if (!Types.isNFT(kind)) { // exclude NFT items from sprite initialization, TODO: create compatible renderer
Warum machen wir das?

Wurde das getestet?

Ist das TODO erledigt?

2022-01-25 19:44 UTC, JaSilasJa commented on client/js/item.js
> +        init: function(id, kind, type, nftData=undefined) {
bitte kommentieren

2022-01-25 19:49 UTC, JaSilasJa commented on client/js/player.js
> +
Besprechungsbedarf zu der Loot-Mechanik von NFTs.

2022-01-25 19:52 UTC, JaSilasJa commented on client/js/player.js
> +        getWeaponNftData: function() {
Bitte kommentieren.

2022-01-25 19:53 UTC, JaSilasJa commented on client/js/player.js
> +        switchWeapon: function(newWeaponName, nftData=undefined) {
Bitte angeben, dass die Methode noch nicht fertig ist.

2022-01-25 19:55 UTC, JaSilasJa commented on client/js/player.js
> +        switchArmor: function(newArmorSprite, nftData=undefined) {
Bitte angeben, dass das noch nicht fertig ist.

2022-01-25 20:01 UTC, JaSilasJa commented on client/js/player.js
> +            if(newWeaponName !== this.getWeaponName() || nftData != undefined) {
Kommentar

2022-01-25 20:01 UTC, JaSilasJa commented on client/js/player.js
> +                if (nftData != undefined) {
Kommentar

2022-01-25 20:05 UTC, JaSilasJa commented on client/js/entity.js
> +        getNftData: function() {
Was ist momentan/final in nftData enthalten?

2022-01-25 20:06 UTC, JaSilasJa commented on client/js/game.js
> +        loadNFTSprite: async function(nftKey) {
Bitte Kommentieren.

2022-01-25 20:12 UTC, JaSilasJa commented on client/js/game.js
> +                self.client.onDropItem(function(item, mobId, nftData=undefined) {
Wurde das schon getestet?

2022-01-25 20:16 UTC, JaSilasJa commented on client/js/items.js
> +        NftArmor: Item.extend({
Die soll raus!

2022-01-25 20:17 UTC, JaSilasJa commented on client/js/sprite.js
> +            if(sprites[name]) {
Kommentar!

2022-01-25 20:20 UTC, JaSilasJa commented on server/js/db_providers/redis.js
> +                            // TODO: Fix meta
Meta ist schon gefixt?

2022-01-25 20:29 UTC, JaSilasJa commented on ts/erdstallclientinterface.ts
> +	// async getNFTs(): Promise< //TODO: implement
Neue Issue verfassen

2022-01-25 20:34 UTC, JaSilasJa commented on ts/metadata.spec.ts
> +    metadata0.name = "test1";
Was passiert hier?

2022-01-25 20:36 UTC, JaSilasJa commented on ts/metadata.ts
>  			allowUpdates: !!cfg.allowUpdates,
Was bedeuten die zwei Ausrufezeichen?

2022-01-25 20:40 UTC, johannesscha commented on ts/metadata.ts
>  			allowUpdates: !!cfg.allowUpdates,
https://brianflove.com/2014-09-02/whats-the-double-exclamation-mark-for-in-javascript/

2022-01-25 20:41 UTC, JaSilasJa commented on ts/metadata.ts
>  		// params is part of the request f.e. http://yadayada.de/yomama?token=0x69696969696969420...
Wir yomama nicht anders geschrieben?

2022-01-25 20:43 UTC, JaSilasJa approved these changes
Martin, das hast du wirklich gut gemacht. Beim nächsten Mal kannst du dich aber um paar mehr Kommentare bemühen. Außerdem wollen wir Oreos.

2022-01-25 22:27 UTC, DeltaTecs commented on client/js/player.js
> +
k

2022-01-25 22:28 UTC, DeltaTecs commented on client/js/player.js
> +        getWeaponNftData: function() {
gone

2022-01-25 22:30 UTC, DeltaTecs commented on client/js/player.js
> +                if (nftData != undefined) {
gone

2022-01-25 22:30 UTC, DeltaTecs commented on client/js/game.js
> +                if (!Types.isNFT(kind)) { // exclude NFT items from sprite initialization, TODO: create compatible renderer
gone

2022-01-25 22:31 UTC, DeltaTecs commented on client/js/player.js
> +        getWeaponNftData: function() {
gone

2022-01-25 22:31 UTC, DeltaTecs commented on client/js/player.js
> +                if (nftData != undefined) {
gone

2022-01-25 22:35 UTC, DeltaTecs commented on client/js/game.js
> +                    if(self.renderer.upscaledRendering) {
hä.
die ecke is auf nem anderen branch geändert deswegen mach ich erst mal nix, aber das willst du da haben?

2022-01-25 22:37 UTC, DeltaTecs commented on client/js/game.js
> +                self.client.onDropItem(function(item, mobId, nftData=undefined) {
habs rausgenommen, hoffentlich is es jetz nich broke

2022-01-25 22:39 UTC, DeltaTecs commented on client/js/sprite.js
> +            if(sprites[name]) {
in anderem Branch umgeschrieben

2022-01-25 22:41 UTC, DeltaTecs commented on ts/erdstallclientinterface.ts
> +	// async getNFTs(): Promise< //TODO: implement
https://www.youtube.com/watch?v=_U-0tOqQc1U

2022-01-25 22:42 UTC, DeltaTecs commented on ts/metadata.spec.ts
> +    metadata0.name = "test1";
einfach ignorieren, können wir auch löschen is eh broke

2022-01-25 22:42 UTC, DeltaTecs commented on ts/metadata.spec.ts
> +    metadata0.name = "test1";
ok, gone

2022-01-25 22:42 UTC, DeltaTecs commented on ts/metadata.ts
>  		// params is part of the request f.e. http://yadayada.de/yomama?token=0x69696969696969420...
ligma

2022-01-25 22:42 UTC, DeltaTecs commented on client/js/items.js
> +        NftArmor: Item.extend({
schon weg

2022-01-26 12:13 UTC, johannesscha requested changes

2022-01-26 12:13 UTC, johannesscha commented on server/js/db_providers/redis.js
> +                        erdstallServer.mintNFT().then(function(mintReceipt) {
Todo: erdstallServer error catching + handling

2022-01-26 12:13 UTC, johannesscha commented on server/js/message.js
> +            this.entity.id,
Identation fix

2022-01-26 12:13 UTC, johannesscha commented on shared/js/gametypes.js
>          GOLDENSWORD: 63,
Dateiänderungen nicht in master übertragen

2022-01-26 12:13 UTC, johannesscha commented on ts/itemmeta.ts
> +    public image_data?: string; // unused
Warum unbenutzte Attribute speichern?

2022-01-26 12:13 UTC, johannesscha commented on ts/itemmeta.ts
>  /**
So kann man doch auch einfach auf NFTMeta direkt zugreifen oder? Eventuell mehr an nerd implementation orientieren

2022-01-26 12:13 UTC, johannesscha commented on ts/metadata.ts
> +	private async creatAndSavePng(tokenId: bigint, metaData: RawItemMeta) {
Typo

2022-01-26 12:13 UTC, johannesscha commented on ts/metadata.ts
> +	public generateNFTItemSpriteJSON(meta: RawItemMeta, tokenId: bigint): string | undefined {
Eventuell doppelten code in eine Methode fassen

2022-01-26 12:16 UTC, DeltaTecs commented on client/js/renderer.js
> +
nicht nötig, request geht schon in game.js raus sobald der spawn empfangen raus. Hier wird nur der Fall abgedeckt das die noch nicht fertig geladen hat.

Ich entferne den print

2022-01-26 12:19 UTC, DeltaTecs commented on shared/js/gametypes.js
>          GOLDENSWORD: 63,
pls elaborate

2022-01-29 11:01 UTC, johannesscha approved these changes

2022-01-29 11:03 UTC, merged