Weapon Switch Button
BP-NFT-Game/NFT_Game pull request #49
Opened 2022-02-21 15:01 UTC by NiDoJu

- Implemented Weapon Switch Button and functionality
- Random NFT in the wallet of the player is chosen and equipped
- At least one NFT in the wallet is required, else an error occurs

Closes #35

2022-02-21 16:39 UTC, DeltaTecs requested changes
passt sonst tip top

2022-02-21 16:39 UTC, DeltaTecs commented on client/js/gameclient.js
> +         getNFTSpritesJSON: function(nftKey) {
Leerzeichen zu viel!!!!!!!

2022-02-21 16:40 UTC, JaSilasJa commented on client/js/gameclient.js
> +        getNFTMetadataJSON: function(nftKey) {
was wenn Metadaten nicht existieren?

2022-02-21 16:43 UTC, JaSilasJa approved these changes
sieht ganz gut aus.

2022-02-21 16:43 UTC, JaSilasJa commented on client/js/main.js
> +                    console.log(randomNumber);
vielleicht als eine Zeile und was welcher Wert angibt.

2022-02-23 08:43 UTC, johannesscha requested changes

2022-02-23 08:43 UTC, johannesscha commented on client/js/gameclient.js
> +        getNFTMetadataJSON: function(nftKey) {
Viel doppelter code (vgl. getNFTSpritesJson()), eventuell Methoden mergen und Parameter (getSpritesOnly: boolean) hinzufügen

2022-02-23 08:43 UTC, johannesscha commented on client/js/main.js
> +                erdstallInterface.getNFTs().then(function(owned_nfts) {
Wollten wir das weapon fetching nicht serverseitig machen, damit wir eventuell die Erdstall Abhängigkeit auf der client Seite komplett rausnehmen können? Würde auch die Latenz verringern, da nur eine Remote-Anfrage gestellt werden muss.

2022-02-23 08:43 UTC, johannesscha commented on server/js/player.js
> +
Error handling, falls Types.getKindFromString nicht resolved werden kann (returned dann null)

2022-02-23 08:43 UTC, johannesscha commented on client/js/main.js
> +                    var chosenWeapon = owned_nfts[Math.floor(Math.random() * (owned_nfts.length))];
Warum zufällige Auswahl und nicht den nächsten NFT? Führt glaube ich zu unerwarteter Funktionalität. Man könnte auch die owned_nfts einmal am Anfang abfragen und dann entsprechend updaten, falls der spieler einen NFT beim Transfer einen NFT equipped kriegt, den er noch nicht in der Liste hat. Würde auch bei serverseitiger Implementierung Sinn machen.

2022-02-23 14:09 UTC, johannesscha approved these changes

2022-02-24 18:58 UTC, DeltaTecs requested changes

2022-02-24 18:58 UTC, DeltaTecs commented on client/js/gameclient.js
> +                const url = "http://" + this.host + ":" + this.port + "/metadata/" + (fetchSprite ? "sprites" : "") + "/" + token + "/" + id;
https!

2022-02-26 12:48 UTC, DeltaTecs commented on client/js/gameclient.js
> +                const url = "http://" + this.host + ":" + this.port + "/metadata/" + (fetchSprite ? "sprites" : "") + "/" + token + "/" + id;
Müssen wir später nochmal anpassen, ist zwar jetzt ein Konflikt mit deployment aber beim Testen auf dem Localhost geht nur die http variante (see #52)

2022-02-26 12:48 UTC, DeltaTecs approved these changes

2022-02-26 13:32 UTC, merged