Deployment
BP-NFT-Game/NFT_Game pull request #52
Opened 2022-02-23 19:28 UTC by DeltaTecs

Configs angepasst, alle Protokolle auf TLS support geändert. Es gehen nur https oder wss anfragen

2022-02-23 22:20 UTC, johannesscha approved these changes

2022-02-23 22:20 UTC, johannesscha commented on client/js/config.js
> +    // the game ignores the config either way and defaults to 80 always. So we neeeeds this
Valider point aber professionelle lingo wär besser imo

2022-02-25 13:50 UTC, DeltaTecs commented
Wenn wir das hier mergen können wir local nicht mehr testen weil wir kein SSL lokal haben. Siehe #54

2022-03-01 08:21 UTC, johannesscha requested changes

2022-03-01 08:21 UTC, johannesscha commented on ts/erdstallclientinterface.ts
> +		//const erdOperatorUrl: URL = new URL("wss://" + config.erdOperatorUrl + "/ws");
z.B. mit "use_wss" config variable ersetzen

2022-03-01 09:31 UTC, JaSilasJa approved these changes
Sieht gut aus. Ich hab keine Anmerkung.

2022-03-05 19:28 UTC, merged