Metadata to Nerd store
BP-NFT-Game/NFT_Game pull request #53
Opened 2022-02-25 13:07 UTC by JaSilasJa

2022-02-26 12:46 UTC, DeltaTecs requested changes

2022-02-26 12:46 UTC, DeltaTecs commented on ts/metadata.ts
> +		metadata.setRgbOffset(this.getRandomInt(255), this.getRandomInt(255), this.getRandomInt(255));
RGB offset Berechnung widerspricht der in Zeile 175

2022-02-26 13:31 UTC, DeltaTecs approved these changes

2022-03-01 08:26 UTC, johannesscha requested changes
2 kleine Anmerkungen sonst top

2022-03-05 19:28 UTC, merged