NFT upgrades
BP-NFT-Game/NFT_Game pull request #58
Opened 2022-03-09 18:27 UTC by JaSilasJa

all weapons are NFTs now

better player feedback for new NFTs
on NFT pick up:
chat message: "*new NFT*"
notification: "Check out your new nft on Nerd" (no link)

2022-03-09 18:30 UTC, JaSilasJa commented
@johannesscha ist das Burn für Items die despawnen auch schon implementiert?

Wollen wir die Mechanik, dass man nur besser Items aufheben kann deaktivieren?

2022-03-10 11:59 UTC, DeltaTecs commented
`npm install async-mutex --save-prod`
falls auch bei anderen der async-mutex fehlt

2022-03-10 12:02 UTC, DeltaTecs commented
Man könnte das "True Warrior" Achievement (erstes Waffen aufheben) umbenennen zu NFT Warrior oder so

2022-03-10 12:11 UTC, DeltaTecs commented
![image](https://user-images.githubusercontent.com/27631835/157658196-f7aba19b-8603-4b28-8435-3fc5bf7fba14.png)
Das passiert wenn man ne Feldermaus klatscht die nix droppt glaube ich

![image](https://user-images.githubusercontent.com/27631835/157658377-6daa141c-9830-4c0f-91a2-856b2eac6bbc.png)
Hier hab ich ne kiste aufgemacht

Ich hab eine Axt bekommen die nicht bunt war, kann sein das es ein kleiner Offset war, ich probier gleich nochmal bisschen rum

2022-03-10 12:17 UTC, DeltaTecs requested changes
bisschen bugy, wär nice wenn das mit den gedroppten Items funktionieren würde

Ich kann später bei der Fehlersuche helfen

2022-03-11 17:24 UTC, DeltaTecs approved these changes
top

2022-03-12 09:26 UTC, johannesscha approved these changes
Alles top, gut kommentiert und strukturiert

2022-03-12 09:27 UTC, johannesscha commented
> @johannesscha ist das Burn für Items die despawnen auch schon implementiert?
> 
> Wollen wir die Mechanik, das man nur besser Items aufheben kann, deaktivieren?

Die items werden aktuell erst bei server neu-start geburnt. Finde es auch sinnvoll die Mechanik zu deaktivieren. Mache dazu neue issues

2022-03-12 09:28 UTC, merged