Html
BP-NFT-Game/NFT_Game pull request #62
Opened 2022-03-12 12:38 UTC by johannesscha

- Updated login interface and graphics
- Players now login using only their metamask account, no passwords etc required
- Improved client-side error handling on login

Closes #36 , closes #20

2022-03-12 13:25 UTC, JaSilasJa approved these changes
Sieht alles gut aus.
Fehler Meldungen sind hilfreich und decken alle Fälle ab.
Branding ist auch ersichtlich.

Wollen wir die Credits so behalten?
Vielleicht noch ein Link zum Nerd?

2022-03-12 14:29 UTC, DeltaTecs requested changes
UI sieht richtig nice aus, hab noch ein paar glitches gefunden

1.
![image](https://user-images.githubusercontent.com/27631835/158021858-20a22dc9-0ab3-472f-8d1b-25e099e621e2.png)
Wäre nice wenn da noch ein Leerzeichen zwischen den beiden Fehlern wäre. (vllt wurde der erste auch garnicht zurückgesetzt?) Sonst vllt there is no account associated with your wallet


2.
Der Spieler startet gerade mit der besten Waffe und Rüstung. Das Waffen wechseln scheint auch etwas buggy, es ändert sich das Waffen Icon nicht

2022-03-12 14:30 UTC, DeltaTecs commented on client/css/main.css
> +    /* #sharing a {display:block;float:right;background-size:844px;position:relative;top:-2px;}
auskommentierten code löschen

2022-03-12 14:30 UTC, DeltaTecs commented on client/css/main.css
> +    /* #sharing a:hover {-moz-transform:scale(1.2);-webkit-transform:scale(1.2);-o-transform:scale(1.2);transform:scale(1.2);}
auskommentierten code löschen

2022-03-12 14:30 UTC, DeltaTecs commented on client/css/main.css
> +        /* #sharing {width:240px;} */
auskommentierten code löschen

2022-03-12 14:30 UTC, DeltaTecs commented on client/css/main.css
> +        /* #sharing {width:202px;} */
auskommentierten code löschen

2022-03-12 14:30 UTC, DeltaTecs commented on client/css/main.css
> +        /* #sharing {width:202px;} */
auskommentierten code löschen

2022-03-14 09:37 UTC, DeltaTecs approved these changes
top, in main.css:835 ist noch was auskommentiert aber das juckt nicht

2022-03-14 12:01 UTC, DeltaTecs approved these changes
Rüstung iwie noch bugged aber nicht reproduzierbar

2022-03-14 13:08 UTC, DeltaTecs commented
Alles bugs weg. Falls Rüstung verbugt:

1. Operator neustarten
2. Metamask zurücksetzen
3. NFT Sprites löschen
4. redis server neustarten
5. redis cli > flushdb flushall
6. git pull
7. npm run postinstall
8. npm run start

2022-03-14 13:11 UTC, merged